name: nallagram
description: Insta Clone

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  dropdown_button2: ^1.5.3
  emoji_picker_flutter: ^1.4.0
  file_picker: ^5.2.0+1
  firebase_auth: ^3.3.3
  firebase_core: ^1.24.0
  firebase_messaging: ^11.2.3
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_emoji: ^2.2.1+1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.8.4+1
  like_button: ^2.0.2
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.9
  provider: ^6.0.0
  story_view: ^0.13.1
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 100
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 700
    - family: Billabong
      fonts:
        - asset: fonts/FontsFree-Net-Billabong.ttf
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf
    #- asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
